language: bash

sudo: false

services:
  - docker

env:
  - Dockerfile=1.4/apache
  - Dockerfile=1.4/fpm
  - Dockerfile=1.3/apache
  - Dockerfile=1.3/fpm

before_script:
  - make image dockerfile=$Dockerfile tag=test
  - make deps.bats

script:
  - make test dockerfile=$Dockerfile tag=test

notifications:
  email:
    on_success: never
    on_failure: always
