language: bash

sudo: required

services:
  - docker

script:
  - make image no-cache=yes VERSION=testing
  - make test VERSION=testing

notifications:
  email:
    on_success: never
    on_failure: always
