language: bash

sudo: false

services:
  - docker

env:
  - Dockerfile=1.3/apache
  - Dockerfile=1.3/fpm
  - Dockerfile=1.2/apache
  - Dockerfile=1.2/fpm

before_script:
  - make image DOCKERFILE=$Dockerfile VERSION=test

script:
  - make test DOCKERFILE=$Dockerfile VERSION=test

notifications:
  email:
    on_success: never
    on_failure: always
